# Generated by Django 3.0.3 on 2020-12-09 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateBlogModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=264)),
                ('description', models.CharField(max_length=264)),
                ('pic', models.ImageField(blank=True, upload_to='pics')),
                ('blog', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PublicBlogModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=264)),
                ('description', models.CharField(max_length=264)),
                ('pic', models.ImageField(blank=True, upload_to='pics')),
                ('blog', models.TextField()),
            ],
        ),
    ]
