# Generated by Django 3.0.3 on 2020-12-09 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privateblogmodel',
            name='pic',
            field=models.ImageField(blank=True, upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='publicblogmodel',
            name='pic',
            field=models.ImageField(blank=True, upload_to='pics'),
        ),
    ]
